networks:
    network1:
        name: deployment-onlook_network
        external: true
services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: onlook-nginx
        networks:
            - network1
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d:/etc/nginx/conf.d
            - next_static:/app/apps/web/client/.next/static
volumes:
    next_static:
        external: true
